### ISSUE TITLE
Problems with simultaneous reading from multiple files

### ISSUE THREAD

**Issue by vovochka404** [iterative/morefs#26]
I have a very simple case with reading from several files.
```python
files = ("file1", "file2")
data = []
for file_path in files:
  async with await fs.open_async(file_path, "rb") as f:
    data.append(f.read())

data = gather(data)
```
The problem is that files are already closed when actual reading is happening.
This approcahe works with s3fs, but doesn't with local fs.

Adding `await` for read operations will make this code sequential, with less benefits from async reading.

Is there any ideas how this limitations can be passed by?

**Comment by skshetry** [comment]
Hi, you can use `AsyncExitStack` for this. Even though `s3` works here, it's a good practice to 
use a context manager, as you may leak sockets and file-descriptors.


```python
from contextlib import AsyncExitStack
from asyncio import gather

files = ("file1", "file2")
data = []
async with AsyncExitStack() as stack:
    for file_path in files:
        f = await stack.enter_async_context(await fs.open_async(file_path, "rb"))
		data.append(f.read())
		contents = await gather(*data)
```

Or, you can avoid using contextmanagers at all, but you need to be responsible for closing the file descriptors.
 

```python
from contextlib import AsyncExitStack
from asyncio import gather

files = ("file1", "file2")
data = []
for file_path in files:
    f = await fs.open_async(file_path, "rb")
	data.append(f.read())
contents = await gather(*data)
```

**Comment by skshetry** [comment]
Ideally, I'd create a separate function to read the contents, and use `gather` over that. 

```python
from contextlib import AsyncExitStack
from asyncio import gather

async def _cat_file(path):
	async with fs.open_async(path, "rb"):
        return f.read()

files = ("file1", "file2")
contents = await gather(*(_cat_file(path) for path in files))
```

If you are looking for exactly this, there is `_cat` API that you can use.
```python
contents = await fs._cat(files)
```
